/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Transaction = IDL.Record({
  'paymentMethod' : IDL.Text,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SpendingLimit = IDL.Record({
  'limit' : IDL.Float64,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bankAccountNumber' : IDL.Opt(IDL.Text),
  'balance' : IDL.Float64,
  'name' : IDL.Text,
  'spendingLimits' : IDL.Vec(SpendingLimit),
  'digiPoints' : IDL.Nat,
});
export const Challenge = IDL.Record({
  'id' : IDL.Nat,
  'completed' : IDL.Bool,
  'rewardPoints' : IDL.Nat,
  'description' : IDL.Text,
  'targetAmount' : IDL.Float64,
});
export const LeaderboardEntry = IDL.Record({
  'name' : IDL.Text,
  'user' : IDL.Principal,
  'points' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDigiPoints' : IDL.Func([IDL.Nat], [], []),
  'addTransaction' : IDL.Func([Transaction], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeChallenge' : IDL.Func([IDL.Nat], [], []),
  'createChallenge' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat], [IDL.Nat], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getBankAccount' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'getDigiPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getReferralPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getReferrals' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getSpendingLimits' : IDL.Func([], [IDL.Vec(SpendingLimit)], ['query']),
  'getSupportedCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getTransactions' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'referUser' : IDL.Func([IDL.Principal], [], []),
  'resetUserData' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBankAccount' : IDL.Func([IDL.Text], [], []),
  'setSpendingLimit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'updateBalance' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Transaction = IDL.Record({
    'paymentMethod' : IDL.Text,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SpendingLimit = IDL.Record({
    'limit' : IDL.Float64,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bankAccountNumber' : IDL.Opt(IDL.Text),
    'balance' : IDL.Float64,
    'name' : IDL.Text,
    'spendingLimits' : IDL.Vec(SpendingLimit),
    'digiPoints' : IDL.Nat,
  });
  const Challenge = IDL.Record({
    'id' : IDL.Nat,
    'completed' : IDL.Bool,
    'rewardPoints' : IDL.Nat,
    'description' : IDL.Text,
    'targetAmount' : IDL.Float64,
  });
  const LeaderboardEntry = IDL.Record({
    'name' : IDL.Text,
    'user' : IDL.Principal,
    'points' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDigiPoints' : IDL.Func([IDL.Nat], [], []),
    'addTransaction' : IDL.Func([Transaction], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeChallenge' : IDL.Func([IDL.Nat], [], []),
    'createChallenge' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getBankAccount' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallenges' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'getDigiPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getReferralPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getReferrals' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getSpendingLimits' : IDL.Func([], [IDL.Vec(SpendingLimit)], ['query']),
    'getSupportedCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getTransactions' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'referUser' : IDL.Func([IDL.Principal], [], []),
    'resetUserData' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBankAccount' : IDL.Func([IDL.Text], [], []),
    'setSpendingLimit' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'updateBalance' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };