/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Challenge {
  'id' : bigint,
  'completed' : boolean,
  'rewardPoints' : bigint,
  'description' : string,
  'targetAmount' : number,
}
export interface LeaderboardEntry {
  'name' : string,
  'user' : Principal,
  'points' : bigint,
}
export interface SpendingLimit { 'limit' : number, 'category' : string }
export interface Transaction {
  'paymentMethod' : string,
  'type' : string,
  'description' : string,
  'timestamp' : bigint,
  'category' : string,
  'amount' : number,
}
export interface UserProfile {
  'bankAccountNumber' : [] | [string],
  'balance' : number,
  'name' : string,
  'spendingLimits' : Array<SpendingLimit>,
  'digiPoints' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDigiPoints' : ActorMethod<[bigint], undefined>,
  'addTransaction' : ActorMethod<[Transaction], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeChallenge' : ActorMethod<[bigint], undefined>,
  'createChallenge' : ActorMethod<[string, number, bigint], bigint>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getBankAccount' : ActorMethod<[], [] | [string]>,
  'getCallerBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChallenges' : ActorMethod<[], Array<Challenge>>,
  'getDigiPoints' : ActorMethod<[], bigint>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getReferralPoints' : ActorMethod<[], bigint>,
  'getReferrals' : ActorMethod<[], Array<Principal>>,
  'getSpendingLimits' : ActorMethod<[], Array<SpendingLimit>>,
  'getSupportedCategories' : ActorMethod<[], Array<string>>,
  'getTransactions' : ActorMethod<[[] | [string]], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'referUser' : ActorMethod<[Principal], undefined>,
  'resetUserData' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBankAccount' : ActorMethod<[string], undefined>,
  'setSpendingLimit' : ActorMethod<[string, number], undefined>,
  'updateBalance' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];